import express from 'express';
import path from 'path';
import fs from 'fs';
import { spawn, spawnSync } from 'child_process';
import crypto from 'crypto';
import got from 'got';
import { MinecraftServerManager, NodeAdapter } from 'minecraft-core';
import config from '../config.js';
import { success, error, ErrorCodes } from '../utils/response.js';
import { getRecommendedJavaVersion, findJavaPath } from '../utils/java-detector.js';
import { InstanceModel } from '../db/index.js';
import { atomicWriteFile } from '../services/mc_server.js';
import { deployRequestSchema } from '@mc-commander/schemas';
import { validateBody } from '../middleware/validate.js';

const mcCoreManager = new MinecraftServerManager(new NodeAdapter());

const PAPER_API_BASE = 'https://api.papermc.io/v3';
const PAPER_USER_AGENT = 'MC_Commander/0.1.0 (https://github.com/wyyfzb/mc-commander)';

async function getPaperVersions() {
  const data = await got(`${PAPER_API_BASE}/projects/paper`, {
    headers: { 'User-Agent': PAPER_USER_AGENT },
    timeout: { request: 15000 },
    retry: { limit: 2 }
  }).json();
  // v3 响应格式：{ project: 'paper', versions: { '1.21': ['1.21.4', '1.21.3', ...], '1.20': [...], ... } }
  // versions 是对象，键是版本组，值是该组下的具体版本号数组
  const versionsObj = data.versions;
  let flatVersions = [];
  if (versionsObj && typeof versionsObj === 'object' && !Array.isArray(versionsObj)) {
    // 展开所有版本组为扁平数组
    for (const groupVersions of Object.values(versionsObj)) {
      if (Array.isArray(groupVersions)) {
        flatVersions.push(...groupVersions);
      }
    }
  } else if (Array.isArray(versionsObj)) {
    flatVersions = versionsObj;
  }
  // 过滤掉 rc/snapshot 等预发布版本，只保留正式版本（不含 '-'）
  const releases = flatVersions.filter(v => !v.includes('-'));
  return releases.slice(0, 30);
}

async function getPaperBuild(mcVersion) {
  const data = await got(`${PAPER_API_BASE}/projects/paper/versions/${mcVersion}/builds`, {
    headers: { 'User-Agent': PAPER_USER_AGENT },
    timeout: { request: 15000 },
    retry: { limit: 2 }
  }).json();
  // v3 响应直接是构建数组（非 {builds: [...]} 结构）
  const builds = Array.isArray(data) ? data : (data.builds || []);
  const stable = builds.filter(b => b.channel === 'STABLE' || b.channel === 'RECOMMENDED');
  const candidates = stable.length > 0 ? stable : builds;
  if (candidates.length === 0) return null;
  // 按 id 降序取最新（v3 用 id 字段，非 build）
  const latest = candidates.sort((a, b) => (b.id || 0) - (a.id || 0))[0];
  return latest;
}

async function getPaperDownloadUrl(mcVersion) {
  const build = await getPaperBuild(mcVersion);
  if (!build) throw new Error(`No Paper build found for ${mcVersion}`);
  const downloads = build.downloads || {};
  const downloadInfo = downloads['server:default'] || downloads.application;
  if (downloadInfo && downloadInfo.url) {
    return downloadInfo.url;
  }
  // 回退到 v2 URL 格式（v3 用 id 字段）
  const buildNum = build.id || build.build;
  const fileName = downloadInfo?.name || `paper-${mcVersion}-${buildNum}.jar`;
  return `https://api.papermc.io/v2/projects/paper/versions/${mcVersion}/builds/${buildNum}/downloads/${fileName}`;
}

async function downloadWithProgress(url, destPath, serverManager, stage = 'download') {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(destPath);
    const stream = got.stream(url, {
      timeout: { request: 120000 },
      retry: { limit: 2 },
      headers: { 'User-Agent': 'MC_Commander/0.1.0 (https://github.com/wyyfzb/mc-commander)' }
    });

    // 下载进度节流：got 的 downloadProgress 每个 chunk 触发（大 jar 每秒可达多次），
    // 全部广播会对所有在线客户端高频轰炸。节流：百分比变化 ≥1% 才发射
    let lastPct = -1;
    stream.on('downloadProgress', ({ percent, transferred, total }) => {
      const pct = percent > 0 ? percent : (total > 0 ? transferred / total : 0);
      if (pct - lastPct < 0.01) return;
      lastPct = pct;
      serverManager.emit('deployProgress', {
        stage,
        percent: pct,
        transferred,
        total
      });
    });

    stream.pipe(file);

    file.on('finish', () => {
      file.close();
      serverManager.emit('deployProgress', {
        stage: 'download_complete',
        percent: 1.0,
        transferred: 0,
        total: 0
      });
      resolve(destPath);
    });

    stream.on('error', (err) => {
      file.close();
      if (fs.existsSync(destPath)) fs.unlinkSync(destPath);
      reject(err);
    });

    file.on('error', (err) => {
      stream.destroy();
      if (fs.existsSync(destPath)) fs.unlinkSync(destPath);
      reject(err);
    });
  });
}

function generateServerProperties(instanceId, _mcVersion) {
  // 生成随机 RCON 密码（16 位十六进制），确保 RCON 默认可用
  // RCON 是 MC Commander 获取玩家坐标/血量、世界时间等数据的核心通道
  const rconPassword = crypto.randomBytes(8).toString('hex');
  return `# Minecraft server properties
# Generated by MC_Commander
enable-jmx-monitoring=false
rcon.port=${25575 + parseInt(instanceId.slice(-4), 16) % 100}
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings=
enforce-secure-profile=true
level-name=world
motd=A Minecraft Server managed by MC_Commander
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=${25565 + parseInt(instanceId.slice(-4), 16) % 100}
enable-rcon=true
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=${rconPassword}
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla
texture-pack=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
`;
}

async function runFirstLaunch(instancePath, javaPath, jarFile, maxMemory) {
  return new Promise((resolve, _reject) => {
    const logsDir = path.join(instancePath, 'logs');
    if (fs.existsSync(logsDir)) {
      return resolve();
    }

    const args = [
      `-Xmx${maxMemory}`,
      `-Xms${maxMemory}`,
      '-jar', jarFile,
      'nogui',
    ];

    const proc = spawn(javaPath, args, {
      cwd: instancePath,
      // 不用 spawn 的 timeout 选项：Node 内部超时仅杀主进程（Windows 上
      // TerminateProcess），且其内部定时器先于自定义定时器触发——根进程先死
      // 会让下方 taskkill /T 无法递归定位整棵树。超时终止统一由下方自定义
      // 定时器按进程树处理（策略同 services/mc_server.js kill()）。
      // Linux/macOS：以独立进程组启动（pid 即 PGID），超时后按进程组终止；
      // Windows 不设 detached（无进程组信号概念），进程树由 taskkill /T 终止。
      ...(process.platform !== 'win32' ? { detached: true } : {}),
    });

    let output = '';
    proc.stdout.on('data', (data) => output += data.toString());
    proc.stderr.on('data', (data) => output += data.toString());

    const timeout = setTimeout(() => {
      // 只杀主进程不够：MC 1.18+/26.x 官方 server.jar 为 Bundler 结构，
      // java 主进程（BundlerMain 引导器）经 ProcessBuilder 派生真正运行的
      // 服务器 JVM，仅杀主进程会遗留孤儿 JVM 继续运行（占端口/写世界数据）。
      // 与 services/mc_server.js kill() 相同的进程树终止策略：
      // Windows 用 taskkill /T 递归终止整棵树；Linux/macOS 因 spawn 带
      // detached:true（pid 即 PGID）用 kill(-pid) 终止整个进程组。
      // 旧版（1.17-）server.jar 直接运行服务器主类、无派生进程，进程树终止
      // 对其同样有效，保持新旧版本兼容。
      const pid = proc.pid;
      if (pid) {
        if (process.platform === 'win32') {
          try { spawnSync('taskkill', ['/F', '/T', '/PID', String(pid)], { stdio: 'ignore' }); } catch {}
        } else {
          try { process.kill(-pid, 'SIGKILL'); } catch {}
        }
      }
      // 单进程 SIGKILL 兜底（进程树终止失败/pid 缺失时仍杀主进程本身）
      try { proc.kill('SIGKILL'); } catch {}
      console.warn('First launch timed out (60s), but config may have been generated');
      resolve();
    }, 60000);

    proc.on('exit', (code) => {
      clearTimeout(timeout);
      if (fs.existsSync(logsDir) || code === 0) {
        resolve();
      } else {
        console.warn(`First launch exited with code ${code}. Output: ${output.substring(0, 500)}`);
        resolve();
      }
    });

    proc.on('error', (err) => {
      clearTimeout(timeout);
      console.warn('First launch error:', err.message);
      resolve();
    });
  });
}

export function createServerJarRoutes(serverManager) {
  const router = express.Router();

  router.get('/versions', async (req, res) => {
    const type = (req.query.type || 'vanilla').toLowerCase();
    try {
      if (type === 'paper') {
        const versions = await getPaperVersions();
        return res.json(success({ type: 'paper', versions }));
      }

      if (type === 'vanilla') {
        // Vanilla 使用 Mojang 官方 manifest 并过滤 release 版本（minecraft-core 返回包含 snapshot）
        const manifest = await got('https://piston-meta.mojang.com/mc/game/version_manifest_v2.json', {
          timeout: { request: 15000 },
          retry: { limit: 2 }
        }).json();
        const releases = manifest.versions
          .filter(v => v.type === 'release')
          .slice(0, 30)
          .map(v => v.id);
        return res.json(success({ type: 'vanilla', versions: releases }));
      }

      if (type === 'fabric') {
        const rawVersions = await mcCoreManager.getVersions('fabric');
        const versions = Array.isArray(rawVersions) ? rawVersions : (rawVersions.versions || Object.keys(rawVersions));
        let loaders = [];
        try {
          const loaderData = await got('https://meta.fabricmc.net/v2/versions/loader', {
            timeout: { request: 15000 },
            retry: { limit: 2 }
          }).json();
          loaders = loaderData.filter(v => v.stable).map(v => v.version).slice(0, 10);
        } catch {}
        return res.json(success({ type: 'fabric', versions: versions.slice(0, 30), loaders }));
      }

      if (type === 'forge') {
        const promotions = await got('https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json', {
          timeout: { request: 15000 },
          retry: { limit: 2 }
        }).json();
        const versions = [...new Set(
          Object.keys(promotions.promos || {})
            .map(v => v.replace(/-(latest|recommended)$/, ''))
        )].filter(v => v.startsWith('1.')).reverse().slice(0, 30);
        return res.json(success({ type: 'forge', versions }));
      }

      const rawVersions = await mcCoreManager.getVersions(type);
      const versions = Array.isArray(rawVersions) ? rawVersions : (rawVersions.versions || Object.keys(rawVersions));
      return res.json(success({ type, versions: versions.slice(0, 30) }));
    } catch (e) {
      console.error(`Failed to fetch ${type} versions:`, e.message);
      return res.status(502).json(error(ErrorCodes.SERVER_ERROR, `Failed to fetch versions: ${e.message}`));
    }
  });

  // 部署实例（请求体 schema parse 校验：type 枚举/必填字段由 deployRequestSchema 单源定义）
  router.post('/instances/deploy', validateBody(deployRequestSchema), async (req, res) => {
    const { type, mcVersion, instanceName, maxMemory, loaderVersion } = req.body;

    const instanceId = `${type}-${crypto.randomBytes(4).toString('hex')}`;
    const instancePath = path.join(config.serversDir, instanceId);

    const isForge = type.toLowerCase() === 'forge';
    const downloadJarName = isForge ? 'forge-installer.jar' : 'server.jar';
    const jarPath = path.join(instancePath, downloadJarName);

    try {
      // 必须在 try 内：mkdirSync 抛错（ENOTDIR/EACCES/EPERM）时由 catch 统一返回 502 并清理，
      // 否则裸 async handler 的 rejection 不被 Express 4 捕获 → 请求挂起 + unhandledRejection
      fs.mkdirSync(instancePath, { recursive: true });
      console.log(`Deploying ${type} ${mcVersion} as ${instanceId}...`);

      let downloadUrl;
      if (type.toLowerCase() === 'paper') {
        downloadUrl = await getPaperDownloadUrl(mcVersion);
      } else {
        try {
          const build = await mcCoreManager.getLatestBuild(type.toLowerCase(), mcVersion);
          if (build && build.downloads && build.downloads.application && build.downloads.application.url) {
            downloadUrl = build.downloads.application.url;
          } else if (build && build.url) {
            downloadUrl = build.url;
          } else if (build && build.downloadUrl) {
            downloadUrl = build.downloadUrl;
          } else {
            const downloadInfo = await mcCoreManager.downloadServer({
              core: type.toLowerCase(),
              version: mcVersion,
              outputDir: instancePath
            });
            if (downloadInfo && (downloadInfo.path || downloadInfo.filePath)) {
              downloadUrl = null;
            } else if (downloadInfo && downloadInfo.url) {
              downloadUrl = downloadInfo.url;
            }
          }
        } catch (mcErr) {
          console.error(`minecraft-core failed for ${type}:`, mcErr.message);
          if (type.toLowerCase() === 'fabric') {
            const loader = loaderVersion || '0.16.10';
            downloadUrl = `https://meta.fabricmc.net/v2/versions/loader/${mcVersion}/${loader}/1.0.1/server/jar`;
          } else if (type.toLowerCase() === 'purpur') {
            downloadUrl = `https://api.purpurmc.org/v2/purpur/${mcVersion}/latest/download`;
          } else {
            throw mcErr;
          }
        }
      }

      if (downloadUrl) {
        console.log(`Download URL: ${downloadUrl}`);
        await downloadWithProgress(downloadUrl, jarPath, serverManager, 'download');
      } else {
        const downloadedFile = fs.readdirSync(instancePath).find(f => f.endsWith('.jar'));
        if (downloadedFile && downloadedFile !== downloadJarName) {
          fs.renameSync(path.join(instancePath, downloadedFile), jarPath);
        }
      }

      const ramSize = maxMemory || '2G';
      const javaVersion = getRecommendedJavaVersion(mcVersion);
      const javaPath = findJavaPath(javaVersion);

      let jarFile = 'server.jar';

      if (isForge) {
        console.log('Forge detected, extracting server files...');
        serverManager.emit('deployProgress', { stage: 'forge_install', percent: 0, transferred: 0, total: 0 });
        const extractArgs = ['-Xmx512M', '-jar', downloadJarName, '--installServer'];
        const extractProc = spawn(javaPath, extractArgs, { cwd: instancePath });
        await new Promise((resolve, reject) => {
          const timer = setTimeout(() => {
            extractProc.kill();
            reject(new Error('Forge installer timed out (120s)'));
          }, 120000);
          extractProc.on('exit', (code) => {
            clearTimeout(timer);
            if (code !== 0) console.warn(`Forge installer exited with code ${code}`);
            resolve();
          });
          extractProc.on('error', (err) => {
            clearTimeout(timer);
            reject(err);
          });
        });

        const forgeJar = fs.readdirSync(instancePath).find(
          f => f.startsWith('forge-') && f.endsWith('.jar') && !f.includes('installer')
        );
        if (forgeJar) {
          jarFile = forgeJar;
        } else {
          throw new Error('Forge server jar not found after install');
        }
        fs.unlinkSync(jarPath);
      }

      const instanceConfig = {
        id: instanceId,
        name: instanceName || `${type.charAt(0).toUpperCase() + type.slice(1)} Server`,
        type: type.toLowerCase(),
        jarFile,
        maxMemory: ramSize,
        minMemory: Math.max(Math.floor(ramSize.replace('G', '')) / 2, 1) + 'G',
        mcVersion,
        loaderVersion: loaderVersion || undefined,
        javaVersion,
        javaPath,
      };

      atomicWriteFile(path.join(instancePath, 'instance.json'), JSON.stringify(instanceConfig, null, 2));
      fs.writeFileSync(path.join(instancePath, 'eula.txt'), 'eula=true\n');
      fs.writeFileSync(path.join(instancePath, 'server.properties'), generateServerProperties(instanceId, mcVersion));

      try {
        InstanceModel.create({
          id: instanceId,
          name: instanceConfig.name,
          type: type.toLowerCase(),
          jarFile,
          javaPath,
          maxMemory: ramSize,
          minMemory: instanceConfig.minMemory,
          serverPath: instancePath,
          mcVersion,
          port: 25565 + parseInt(instanceId.slice(-4), 16) % 100,
        });
        console.log(`Instance ${instanceId} written to DB`);
      } catch (dbErr) {
        console.warn(`Failed to write instance to DB:`, dbErr.message);
      }

      serverManager.emit('deployProgress', { stage: 'first_launch', percent: 0, transferred: 0, total: 0 });
      try {
        console.log('Running first launch to generate config...');
        await runFirstLaunch(instancePath, javaPath, jarFile, ramSize);
        console.log('First launch completed');
      } catch (e) {
        console.warn('First launch failed (may require manual setup):', e.message);
      }

      serverManager.loadInstances();

      serverManager.emit('deployProgress', { stage: 'complete', percent: 1.0, transferred: 0, total: 0 });
      console.log(`Instance ${instanceId} deployed successfully`);

      res.json(success({
        id: instanceId,
        name: instanceConfig.name,
        type: type.toLowerCase(),
        mcVersion,
        javaVersion,
        path: instancePath,
        maxMemory: ramSize,
      }, 'Instance deployed successfully'));
    } catch (e) {
      // 清理失败（Windows 上目录被进程占用——如孤儿 JVM 仍在写文件——或权限
      // 不足时 rmSync 抛 EPERM/EBUSY）必须兜住：异常从 catch 逃逸会变成 async
      // rejection，Express 4 不捕获 → 请求挂起 + unhandledRejection 崩溃
      // （与上方 L312-314 mkdirSync 同源问题）。清理失败仅记录日志，仍返回 502。
      try {
        fs.rmSync(instancePath, { recursive: true, force: true });
      } catch (cleanupErr) {
        console.warn('Failed to clean up instance dir after failed deploy:', cleanupErr.message);
      }
      serverManager.emit('deployProgress', { stage: 'error', percent: 0, transferred: 0, total: 0, error: e.message });
      console.error(`Failed to deploy ${type} ${mcVersion}:`, e.message);
      return res.status(502).json(error(ErrorCodes.SERVER_ERROR, `Deployment failed: ${e.message}`));
    }
  });

  return router;
}
