/**
 * @mc-commander/schemas — 共享 zod 契约定义
 * API/WS/通知三方同源，根治契约漂移
 */

// 信封
export {
  paginationSchema,
  apiEnvelopeSchema,
  apiErrorEnvelopeSchema,
  makeApiEnvelopeSchema,
  nullDataSchema,
  type Pagination,
  type ApiEnvelope,
  type ApiErrorEnvelope,
  type NullData,
} from './envelope'

// 玩家
export {
  playerSchema,
  playerListSchema,
  playerDetailsResponseSchema,
  banRecordSchema,
  banRecordListSchema,
  banResponseBodySchema,
  banRequestBodySchema,
  spawnPointSchema,
  playerPositionSchema,
  playerEventSchema,
  playerSessionSchema,
  playerStatsSchema,
  playerPotionEffectSchema,
  ipHistoryEntrySchema,
  inventoryItemSchema,
  playerInventorySchema,
  playerDimensionSchema,
  playerGameModeSchema,
  weatherTypeSchema,
  type Player,
  type PlayerList,
  type PlayerDetailsResponse,
  type BanRecord,
  type BanRecordList,
  type BanResponseBody,
  type BanRequestBody,
  type SpawnPoint,
  type PlayerPosition,
  type PlayerDimension,
  type PlayerGameMode,
  type WeatherType,
  type PlayerEvent,
  type PlayerSession,
  type PlayerStats,
  type PlayerPotionEffect,
  type IpHistoryEntry,
  type InventoryItem,
  type PlayerInventory,
} from './player'

// 实例
export {
  instanceSummarySchema,
  instanceStatusSchema,
  instanceStatusListSchema,
  instanceUpdatePayloadSchema,
  instanceSettingsRequestBodySchema,
  instanceStartRequestBodySchema,
  instanceCommandRequestBodySchema,
  instancePropertiesRequestBodySchema,
  instanceEulaRequestBodySchema,
  pushChannelStateSchema,
  pushChannelRequestBodySchema,
  pushChannelToggleResponseSchema,
  instanceDeleteRequestBodySchema,
  instanceDeleteResponseSchema,
  crashArtifactSchema,
  crashArtifactFieldSchema,
  overviewDataSchema,
  logEntrySchema,
  logEntriesSchema,
  commandResponseSchema,
  type InstanceSummary,
  type InstanceStatus,
  type InstanceStatusList,
  type CrashArtifact,
  type CrashArtifactField,
  type InstanceUpdatePayload,
  type InstanceSettingsRequestBody,
  type InstanceStartRequestBody,
  type InstanceCommandRequestBody,
  type InstancePropertiesRequestBody,
  type InstanceEulaRequestBody,
  type InstanceDeleteRequestBody,
  type InstanceDeleteResponse,
  type OverviewData,
  type LogEntry,
  type LogEntries,
  type CommandResponse,
} from './instance'

// 备份
export {
  backupItemSchema,
  backupCreateRequestSchema,
  backupRestoreRequestSchema,
  archivedSnapshotGroupSchema,
  archivedSnapshotListSchema,
  backupAttachRequestSchema,
  backupAttachResponseSchema,
  backupCancelResponseSchema,
  restoreConfirmTarget,
  type BackupItem,
  type BackupCreateRequest,
  type BackupRestoreRequest,
  type ArchivedSnapshotGroup,
  type BackupAttachRequest,
  type BackupAttachResponse,
  type BackupCancelResponse,
} from './backup'

// 定时任务
export {
  scheduledTaskSchema,
  scheduledTaskTypeSchema,
  taskCreatePayloadSchema,
  taskUpdatePayloadSchema,
  taskRunHistorySchema,
  taskRunHistoryListSchema,
  taskRunStatusSchema,
  type ScheduledTask,
  type ScheduledTaskType,
  type TaskCreatePayload,
  type TaskRunHistory,
  type TaskRunHistoryList,
  type TaskRunStatus,
  type TaskUpdatePayload,
} from './task'

export {
  systemMetricSampleSchema,
  systemMetricsSeriesSchema,
  type SystemMetricSample,
  type SystemMetricsSeries,
} from './metrics'

// WebSocket
export {
  WS_EVENT_TYPES,
  wsEventTypeSchema,
  wsMessageSchema,
  wsStatusSnapshotSchema,
  wsPerformancePayloadSchema,
  wsLogPayloadSchema,
  wsStatusEventPayloadSchema,
  wsPlayerEventPayloadSchema,
  wsWeatherPayloadSchema,
  wsBackupPayloadSchema,
  wsBackupProgressPayloadSchema,
  NOTIFICATION_EVENT_TYPES,
  type WsEventType,
  type WsMessage,
  type WsStatusSnapshot,
  type WsPerformancePayload,
  type WsLogPayload,
  type WsStatusEventPayload,
  type WsPlayerEventPayload,
  type WsWeatherPayload,
  type WsBackupPayload,
  type WsBackupProgressPayload,
} from './ws'

// 世界
export {
  worldInfoSchema,
  worldDimensionSchema,
  serverPropertiesSchema,
  updatePropertiesResponseSchema,
  type WorldInfo,
  type WorldDimension,
  type ServerPropertiesMap,
  type ServerProperties,
  type UpdatePropertiesResponse,
} from './world'

// 文件
export {
  fileEntrySchema,
  fileListResponseSchema,
  fileInfoResponseSchema,
  fileContentResponseSchema,
  fileSaveResponseSchema,
  fileMkdirResponseSchema,
  fileRenameResponseSchema,
  fileUploadResponseSchema,
  fileListRequestSchema,
  filePathRequestSchema,
  fileSaveRequestSchema,
  fileMkdirRequestSchema,
  fileRenameRequestSchema,
  fileUploadQuerySchema,
  type FileEntry,
  type FileListResponse,
  type FileInfoResponse,
  type FileContentResponse,
  type FileSaveResponse,
  type FileMkdirResponse,
  type FileRenameResponse,
  type FileUploadResponse,
  type FileListRequest,
  type FilePathRequest,
  type FileSaveRequest,
  type FileMkdirRequest,
  type FileRenameRequest,
  type FileUploadQuery,
} from './files'

// 审计
export {
  auditLogItemSchema,
  commandHistoryItemSchema,
  auditLogsQuerySchema,
  commandHistoryQuerySchema,
  type AuditLogItem,
  type CommandHistoryItem,
} from './audit'

// Webhook
export {
  WEBHOOK_PLATFORMS,
  webhookPlatformSchema,
  webhookSchema,
  webhookCreatePayloadSchema,
  webhookDeliverySchema,
  webhookTestResultSchema,
  type WebhookPlatform,
  type Webhook,
  type WebhookCreatePayload,
  type WebhookDelivery,
  type WebhookTestResult,
} from './webhook'

// 部署/升级
export {
  versionsResponseSchema,
  deployRequestSchema,
  deployResultSchema,
  deployProgressSchema,
  deployCancelRequestSchema,
  deployCancelResponseSchema,
  deployStatusResponseSchema,
  upgradeStageSchema,
  upgradeProgressSchema,
  upgradeRequestSchema,
  upgradeStartResponseSchema,
  upgradeCancelResponseSchema,
  upgradeStatusResponseSchema,
  type VersionsResponse,
  type DeployRequest,
  type DeployResult,
  type DeployProgress,
  type DeployCancelRequest,
  type DeployCancelResponse,
  type DeployStatusResponse,
  type UpgradeStage,
  type UpgradeProgress,
  type UpgradeRequest,
  type UpgradeStartResponse,
  type UpgradeCancelResponse,
  type UpgradeStatusResponse,
} from './deploy'

// 插件
export {
  pluginMetaSchema,
  pluginInfoSchema,
  pluginListSchema,
  pluginUpdateStatusSchema,
  pluginUpdateCheckResultSchema,
  pluginToggleResultSchema,
  pluginDeleteResultSchema,
  pluginUploadResultSchema,
  marketSearchHitSchema,
  marketSearchResultSchema,
  marketVersionFileSchema,
  marketVersionSchema,
  marketVersionsResultSchema,
  marketInstallResultSchema,
  marketSearchRequestSchema,
  marketVersionsRequestSchema,
  pluginOverwriteQuerySchema,
  marketInstallRequestSchema,
  pluginEnabledRequestSchema,
  type PluginMeta,
  type PluginInfo,
  type PluginList,
  type PluginUpdateStatus,
  type PluginUpdateCheckResult,
  type PluginToggleResult,
  type PluginDeleteResult,
  type PluginUploadResult,
  type MarketSearchHit,
  type MarketSearchResult,
  type MarketVersionFile,
  type MarketVersion,
  type MarketVersionsResult,
  type MarketInstallResult,
  type MarketSearchRequest,
  type MarketVersionsRequest,
  type PluginOverwriteQuery,
  type MarketInstallRequest,
  type PluginEnabledRequest,
} from './plugin'

// 系统
export {
  diskInfoSchema,
  diskUsageSchema,
  diskAlertThresholdsSchema,
  memoryAlertThresholdsSchema,
  systemStatsSchema,
  updateCheckResultSchema,
  type DiskInfo,
  type DiskUsage,
  type DiskAlertThresholds,
  type MemoryAlertThresholds,
  type SystemStats,
  type UpdateCheckResult,
} from './system'

// 认证与 API Key
export {
  authSessionResponseSchema,
  authSetupResponseSchema,
  authStatusResponseSchema,
  authCapabilitiesResponseSchema,
  authPasswordChangeResponseSchema,
  authLogoutResponseSchema,
  authSessionItemSchema,
  authSessionsResponseSchema,
  authSessionKickResponseSchema,
  apiKeyRotateResponseSchema,
  machineScopeSchema,
  machineCredentialSchema,
  machineCredentialListSchema,
  machineCredentialCreateResponseSchema,
  machineCredentialCreateBodySchema,
  machineCredentialToggleBodySchema,
  machineCredentialSelfSchema,
  authSetupRequestBodySchema,
  authLoginRequestBodySchema,
  authPasswordChangeRequestBodySchema,
  authTotpStatusResponseSchema,
  authTotpEnrollResponseSchema,
  authTotpConfirmRequestBodySchema,
  authTotpConfirmResponseSchema,
  authTotpDisableRequestBodySchema,
  authTotpDisableResponseSchema,
  type AuthSessionResponse,
  type AuthSetupResponse,
  type AuthStatusResponse,
  type AuthCapabilitiesResponse,
  type AuthPasswordChangeResponse,
  type AuthLogoutResponse,
  type AuthSessionItem,
  type AuthSessionsResponse,
  type AuthSessionKickResponse,
  type ApiKeyRotateResponse,
  type MachineScope,
  type MachineCredential,
  type MachineCredentialList,
  type MachineCredentialCreateResponse,
  type MachineCredentialCreateBody,
  type MachineCredentialToggleBody,
  type MachineCredentialSelf,
  type AuthSetupRequestBody,
  type AuthLoginRequestBody,
  type AuthPasswordChangeRequestBody,
  type AuthTotpStatusResponse,
  type AuthTotpEnrollResponse,
  type AuthTotpConfirmRequestBody,
  type AuthTotpConfirmResponse,
  type AuthTotpDisableRequestBody,
  type AuthTotpDisableResponse,
} from './auth'
